SELECT * FROM CUSTOMER ;
INSERT INTO CUSTOMER (CUST_ID,ACCOUNT_NUMBER ,ADDRESS,AGE ,BALANCE ,NAME ,TYPE)
VALUES (1,111,'Uppal', 25, 125000.00,'Ramu','Savings' );
INSERT INTO CUSTOMER (CUST_ID,ACCOUNT_NUMBER ,ADDRESS,AGE ,BALANCE ,NAME ,TYPE)
VALUES (2,222,'Kukatpally', 21, 55000.00,'Somu','Savings' );
INSERT INTO CUSTOMER (CUST_ID,ACCOUNT_NUMBER ,ADDRESS,AGE ,BALANCE ,NAME ,TYPE)
VALUES (3,333,'Narayanaguda', 25, 60000.00,'Sunny','Savings' );
INSERT INTO CUSTOMER (CUST_ID,ACCOUNT_NUMBER ,ADDRESS,AGE ,BALANCE ,NAME ,TYPE)
VALUES (4,444,'Uppal', 24, 45000.00,'Bunny','Savings' );
--INSERT INTO CUSTOMER (CUST_ID,ACCOUNT_NUMBER ,ADDRESS,AGE ,BALANCE ,NAME ,TYPE)
--VALUES (5,5,'Uppal', 50, 55000.00,'Saketh','Savings' );
--INSERT INTO CUSTOMER (CUST_ID,ACCOUNT_NUMBER ,ADDRESS,AGE ,BALANCE ,NAME ,TYPE)
--VALUES (6,6,'Uppal', 6, 1500.00,'Jai','Savings' );



INSERT INTO PAYEE (PAYEE_ID, IFSCCODE , NICK_NAME , ACCOUNT_NUMBER , CUST_ID , NAME, CUSTOMER_CUST_ID )
VALUES (1,'HDFC001','Jai',333,1,'Bunny',1);


INSERT INTO PAYEE (PAYEE_ID, IFSCCODE , NICK_NAME , ACCOUNT_NUMBER , CUST_ID , NAME, CUSTOMER_CUST_ID )
VALUES (2,'HDFC002','Dim',444,1,'Sunny',1);

INSERT INTO ACCOUNT_SUMMARY (CUST_ID , SUMMARY_ID , REFERENCE_NUMBER , TRANSACTION_DATE , DEBITED_AMOUNT, CREADITED_AMOUNT ,CLOSING_BALANCE, CUSTOMER_CUST_ID)
VALUES (1,1,'OPEN Account','2019-01-25 14:01:00',0,125000,125000,1);

--INSERT INTO ACCOUNT_SUMMARY (SUMMARY_ID , CLOSING_BALANCE , CREADITED_AMOUNT , CUST_ID , DEBITED_AMOUNT, REFERENCE_NUMBER , TRANSACTION_DATE,CUSTOMER_CUST_ID )
--VALUES (2, 15000, 15000, 2, 0, 'OPEN Account','2019-01-25 14:01:00',2);

